## Embedding Adjustment Notebook

This will contain the model to adjust the embedding space in some way to accurately represent user inputs.

Current plan is to use a Neural Network from PyTorch to alter the values of the embeddings to other embeddings with the exact same shape. Building the network is easy, but figuring out the loss function is harder.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np

## Neural Network

This section contains the Neural Network that adjusts the embeddings. This sets up the architecture and tests forward with just basic inputs.

In [2]:
# Architecture of the model (can change)
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Linear(1024, 1024)
        self.layer2 = nn.Linear(1024, 1024)

    def forward(self, x):
        x = self.layer1(x)
        x = nn.functional.relu(x)
        x = self.layer2(x)
        out = nn.functional.sigmoid(x)
        return out

In [3]:
# model and fake inputs
model = Net()
inputs = [[1.0] * 1024] * 5
inputs = torch.tensor(inputs)
print(len(inputs), len(inputs[0]))

5 1024


In [4]:
# runs all inputs in model
for n in inputs:
    input = n.detach().clone()
    print(model(n).detach())

tensor([0.4783, 0.5042, 0.5390,  ..., 0.4840, 0.5078, 0.5458])
tensor([0.4783, 0.5042, 0.5390,  ..., 0.4840, 0.5078, 0.5458])
tensor([0.4783, 0.5042, 0.5390,  ..., 0.4840, 0.5078, 0.5458])
tensor([0.4783, 0.5042, 0.5390,  ..., 0.4840, 0.5078, 0.5458])
tensor([0.4783, 0.5042, 0.5390,  ..., 0.4840, 0.5078, 0.5458])


## Loss Function

This contains how we calculate loss. This section does not have code (maybe it will) but is here to guide the user through the thought process behind the loss.

Current idea is to mark objects that should be close together based on predefined clusters, and objects that the user has specified should be close together. User specified should be weighted much more.

Perhaps in the pre-processing, we have a function that takes each data point and assigns them the label which is the cluster they were assign (arbitrary integer identifier for the cluster). Then which of these data points were specified by the user, these elements will have a much higher weight when claculating the loss.

## Data Preparation

This section contains the necessary pre-processing done on the data

In [5]:
class ClusterDataset(Dataset):
    def __init__(self, inputs, labels, user_specified, mode = 'train'):
        self.mode = mode
        self.user_specified = user_specified
        if self.mode == 'train':
          self.train = inputs.reshape(-1, 1024).float()
          self.train_labels = labels

    def __len__(self):
        return self.train.shape[0]

    def __getitem__(self, idx):
        if self.mode == 'train':
          return {'input': self.train[idx], 'label': self.train_labels[idx], 'user_specified': self.user_specified[idx]}

In [6]:
def load_data(inputs, clusters, user_specified, batch_size):
    train_set = ClusterDataset(inputs, clusters, user_specified)
    train_dataloader = DataLoader(train_set, batch_size=batch_size, shuffle=True)

    return train_dataloader

## NN Training

This will train the network with the loss function defined above, way unfinished

In [50]:
def train_loop(data, epochs, loss_function, optim, batch_size):
    inputs, clusters, user_specified = data
    train_dataloader = load_data(inputs, clusters, user_specified, batch_size)
    init_train_losses = []
    for epoch in range(1,epochs+1):

        #Training phase
        model.train()  #Setting the model to train phase
        train_loss = []
        train_acc = 0.

        for idx, batch in enumerate(train_dataloader):

            inputs = batch['input']
            labels = batch['label']
            user = batch['user_specified']
            outputs = torch.squeeze(model(inputs.float()))

            loss = loss_function(outputs, labels.float(), user_specified)
            loss.backward()
            optim.step()
            train_loss.append(loss.item())
            optim.zero_grad()
        train_acc = train_acc / len(inputs)
        
        if epoch%10==0:
            print("Epoch : {}, Train loss: {}".format(epoch, np.mean(train_loss)))
            init_train_losses.append(np.mean(train_loss))

## Pipeline

This section has the instructions to run the full pipeline from above

format the data like this
a 3-tuple containing tensors with the following shapes ([n, 1024], [n], [n]) where n is the number of samples

The first one is the embeddings of each datapoint

the second one is the id of the cluster they were assigned to

the third is full of 1 or 0, 1 if it was a user-specified input, 0 else

Then specify number of epochs

a loss function from above

and an optimizer

In [51]:
rng = np.random.default_rng(seed=42)
data = (torch.randn(100, 1024), torch.empty(100), torch.empty(100))

print(len(data[0]), len(data[0][0]))
print(data[0][1][1])
for i in range(0,100):
    data[1][i] = rng.integers(0,5)
    data[2][i] = rng.integers(0,1, endpoint=True)
print(len(data[1]), len(data[2]))
print(data[1][0], data[1][2], data[2][0], data[2][1])




100 1024
tensor(-1.1559)
100 100
tensor(0.) tensor(2.) tensor(1.) tensor(0.)


In [54]:
def temp_loss(outputs, labels, user_specified):
    loss = 0
    for i in range(0, len(outputs) - 1):
        if labels[i] == labels[i+1]:
            loss += (outputs[i] - outputs[i+1]).sum()/1024
        else:
            loss += (outputs[i] + outputs[i+1]).sum()/1024
    return loss

In [55]:
batch_size = 32
epochs = 100
loss_function = temp_loss
optim = torch.optim.Adam(model.parameters(), lr = 0.01)
train_loop(data, epochs, loss_function, optim, batch_size)

Epoch : 10, Train loss: 5.933799125254154
Epoch : 20, Train loss: 1.5926065742969513
Epoch : 30, Train loss: 1.4128088653087616
Epoch : 40, Train loss: 1.546630859375
Epoch : 50, Train loss: 1.6640625
Epoch : 60, Train loss: 1.310546875
Epoch : 70, Train loss: 1.4873046875
Epoch : 80, Train loss: 1.35009765625
Epoch : 90, Train loss: 1.44873046875
Epoch : 100, Train loss: 1.5068359375
